export const LOCATIONS_COPY = {
  PAGE_TITLE: 'Locations',
  PAGE_DESCRIPTION: 'Manage all your apartment complexes',
  ADD_LOCATION: 'Add Location',
  DETAIL_TITLE: 'Location Details',
  COMPARISON_TITLE: 'Location Comparison',
  COMPARISON_DESCRIPTION: 'Compare performance across your locations',
  // Table
  COL_NAME: 'Location Name',
  COL_UNITS: 'Units',
  COL_MEMBERS: 'Members',
  COL_STATUS: 'Status',
  COL_MRR: 'MRR',
  COL_MANAGERS: 'Managers',
  COL_ACTIONS: 'Actions',
  // Add location modal
  MODAL_TITLE: 'Add New Location',
  MODAL_DESCRIPTION: 'Create a new apartment complex under your ownership group.',
  FIELD_COMPLEX_NAME: 'Complex Name',
  FIELD_COMPLEX_NAME_PLACEHOLDER: 'e.g. The Meridian',
  FIELD_UNIT_COUNT: 'Number of Units',
  FIELD_UNIT_COUNT_PLACEHOLDER: 'e.g. 150',
  FIELD_PRICE: 'Price per Unit ($/month)',
  FIELD_PRICE_PLACEHOLDER: '3.00',
  FIELD_PRICE_HINT: '$2.00 – $5.00 per unit/month',
  FIELD_ADDRESS: 'Address',
  FIELD_ADDRESS_PLACEHOLDER: 'e.g. 123 Main St, City, State',
  // PM assignment
  FIELD_PM_SECTION: 'Property Manager (optional)',
  FIELD_PM_EXISTING: 'Select existing manager',
  FIELD_PM_NEW: 'Invite new manager',
  FIELD_PM_SKIP: 'Skip — assign later',
  FIELD_PM_SELECT_PLACEHOLDER: 'Select a manager...',
  FIELD_PM_NAME: 'Full Name',
  FIELD_PM_NAME_PLACEHOLDER: 'e.g. Jane Smith',
  FIELD_PM_EMAIL: 'Email Address',
  FIELD_PM_EMAIL_PLACEHOLDER: 'e.g. jane@complex.com',
  FIELD_PM_EMAIL_HINT: 'An invite link will be sent to this address.',
  BTN_SUBMIT: 'Create Location',
  BTN_CANCEL: 'Cancel',
  // Messages
  SUCCESS_CREATED: 'Location created successfully. Super Admin has been notified.',
  ERROR_LOAD: 'Failed to load locations',
  ERROR_LOAD_DESC: 'Could not retrieve your locations.',
  EMPTY_TITLE: 'No locations yet',
  EMPTY_DESC: 'Add your first apartment complex to get started.',
  // Detail
  DETAIL_BACK: 'Back to Locations',
  DETAIL_ERROR: 'Failed to load location details',
  DETAIL_TAB_OVERVIEW: 'Overview',
  DETAIL_TAB_RESIDENTS: 'Residents',
  DETAIL_TAB_MANAGERS: 'Managers',
  DETAIL_TAB_BRANDING: 'Branding',
  // Comparison
  COMPARISON_EMPTY: 'Add at least two locations to compare.',
  COMPARISON_ERROR: 'Failed to load comparison data',
  METRIC_MEMBERS: 'Members',
  METRIC_ACTIVE: 'Active This Week',
  METRIC_OCCUPANCY: 'Occupancy Rate',
  METRIC_MRR: 'MRR',
} as const
