/**
 * MOCK DATA — dashboard preview only.
 * Remove this file and revert the service imports when the real API is connected.
 */

import type { PlatformMetrics, PlatformAnalytics } from './analytics.types'
import type { OnboardingApplication } from '../onboarding/onboarding.types'
import type { SupportTicket } from '../support/support.types'
import type { TenantListItem, OwnerGroupListItem } from '../tenants/tenant.types'
import type { PaginatedResponse } from '@/types/api.types'

export const MOCK_PLATFORM_METRICS: PlatformMetrics = {
  totalTenants: 48,
  activeTenants: 41,
  lapsedTenants: 4,
  trialTenants: 7,
  totalMrr: 62400,
  activeMembers: 3812,
  newSignupsThisMonth: 7,
  trialConversionRate: 68,
  workoutLogsThisMonth: 8420,
  mealLogsThisMonth: 6180,
  mrrTrend: 12,
  tenantTrend: 5,
  memberTrend: 8,
  signupTrend: -3,
  workoutLogTrend: 14,
  mealLogTrend: 9,
  tenantSparkline: [28, 35, 30, 38, 33, 43, 48],
  mrrSparkline: [43000, 52000, 46500, 55000, 50000, 58000, 62400],
  memberSparkline: [2600, 3400, 2900, 3600, 3100, 3500, 3812],
  signupSparkline: [3, 12, 5, 14, 4, 10, 7],
  conversionSparkline: [55, 74, 60, 78, 58, 73, 68],
  workoutLogSparkline: [5200, 7100, 6300, 8900, 7400, 9100, 8420],
  mealLogSparkline: [3800, 5200, 4600, 6400, 5100, 6900, 6180],
}

export const MOCK_ACTIVE_LAPSED_TREND = [
  { month: 'May', active: 32, lapsed: 2 },
  { month: 'Jun', active: 34, lapsed: 2 },
  { month: 'Jul', active: 35, lapsed: 3 },
  { month: 'Aug', active: 37, lapsed: 3 },
  { month: 'Sep', active: 38, lapsed: 3 },
  { month: 'Oct', active: 39, lapsed: 2 },
  { month: 'Nov', active: 40, lapsed: 3 },
  { month: 'Dec', active: 40, lapsed: 3 },
  { month: 'Jan', active: 41, lapsed: 3 },
  { month: 'Feb', active: 42, lapsed: 4 },
  { month: 'Mar', active: 43, lapsed: 4 },
  { month: 'Apr', active: 41, lapsed: 4 },
]

export const MOCK_SIGNUP_TREND = [
  { month: 'May', signups: 3 },
  { month: 'Jun', signups: 8 },
  { month: 'Jul', signups: 5 },
  { month: 'Aug', signups: 11 },
  { month: 'Sep', signups: 6 },
  { month: 'Oct', signups: 9 },
  { month: 'Nov', signups: 13 },
  { month: 'Dec', signups: 4 },
  { month: 'Jan', signups: 10 },
  { month: 'Feb', signups: 7 },
  { month: 'Mar', signups: 12 },
  { month: 'Apr', signups: 7 },
]

export const MOCK_CONVERSION_RATE_TREND = [
  { month: 'May', rate: 55 },
  { month: 'Jun', rate: 62 },
  { month: 'Jul', rate: 58 },
  { month: 'Aug', rate: 70 },
  { month: 'Sep', rate: 64 },
  { month: 'Oct', rate: 72 },
  { month: 'Nov', rate: 68 },
  { month: 'Dec', rate: 60 },
  { month: 'Jan', rate: 74 },
  { month: 'Feb', rate: 69 },
  { month: 'Mar', rate: 75 },
  { month: 'Apr', rate: 68 },
]

export const MOCK_LOG_VOLUME_TREND = [
  { month: 'May', workoutLogs: 4100, mealLogs: 2900 },
  { month: 'Jun', workoutLogs: 5800, mealLogs: 4200 },
  { month: 'Jul', workoutLogs: 5200, mealLogs: 3700 },
  { month: 'Aug', workoutLogs: 7400, mealLogs: 5300 },
  { month: 'Sep', workoutLogs: 6100, mealLogs: 4600 },
  { month: 'Oct', workoutLogs: 7900, mealLogs: 5800 },
  { month: 'Nov', workoutLogs: 8600, mealLogs: 6100 },
  { month: 'Dec', workoutLogs: 6500, mealLogs: 4800 },
  { month: 'Jan', workoutLogs: 9200, mealLogs: 6700 },
  { month: 'Feb', workoutLogs: 7800, mealLogs: 5900 },
  { month: 'Mar', workoutLogs: 9800, mealLogs: 7100 },
  { month: 'Apr', workoutLogs: 8420, mealLogs: 6180 },
]

export const MOCK_PLATFORM_ANALYTICS: PlatformAnalytics = {
  mrrTrend: [
    { month: 'May', mrr: 44000 },
    { month: 'Jun', mrr: 47500 },
    { month: 'Jul', mrr: 46200 },
    { month: 'Aug', mrr: 50100 },
    { month: 'Sep', mrr: 52800 },
    { month: 'Oct', mrr: 51400 },
    { month: 'Nov', mrr: 55000 },
    { month: 'Dec', mrr: 54200 },
    { month: 'Jan', mrr: 57300 },
    { month: 'Feb', mrr: 59100 },
    { month: 'Mar', mrr: 61000 },
    { month: 'Apr', mrr: 62400 },
  ],
  tenantGrowth: [
    { month: 'May', apartment: 18, trainer: 9 },
    { month: 'Jun', apartment: 20, trainer: 10 },
    { month: 'Jul', apartment: 21, trainer: 11 },
    { month: 'Aug', apartment: 23, trainer: 12 },
    { month: 'Sep', apartment: 24, trainer: 13 },
    { month: 'Oct', apartment: 25, trainer: 14 },
    { month: 'Nov', apartment: 27, trainer: 15 },
    { month: 'Dec', apartment: 28, trainer: 15 },
    { month: 'Jan', apartment: 29, trainer: 16 },
    { month: 'Feb', apartment: 31, trainer: 16 },
    { month: 'Mar', apartment: 33, trainer: 17 },
    { month: 'Apr', apartment: 34, trainer: 14 },
  ],
  signupFunnel: [
    { stage: 'Visited', count: 1240 },
    { stage: 'Signed Up', count: 380 },
    { stage: 'Trial Started', count: 210 },
    { stage: 'Converted', count: 143 },
  ],
  topTenantsByMrr: [
    { id: '1', name: 'Riverside Apartments', tenantType: 'apartment', plan: 'pro', mrr: 5800 },
    { id: '2', name: 'FitLife Coaching', tenantType: 'trainer', plan: 'growth', mrr: 4200 },
    { id: '3', name: 'Meridian Living', tenantType: 'apartment', plan: 'pro', mrr: 3900 },
    { id: '4', name: 'Coach Alex Pro', tenantType: 'trainer', plan: 'pro', mrr: 3100 },
    { id: '5', name: 'The Heights Complex', tenantType: 'apartment', plan: 'growth', mrr: 2750 },
  ],
  activeLapsedTrend: MOCK_ACTIVE_LAPSED_TREND,
  signupTrend: MOCK_SIGNUP_TREND,
  conversionRateTrend: MOCK_CONVERSION_RATE_TREND,
  logVolumeTrend: MOCK_LOG_VOLUME_TREND,
}

export const MOCK_ONBOARDING_QUEUE: PaginatedResponse<OnboardingApplication> = {
  data: [
    {
      id: 'ob-1',
      tenantName: 'Oakwood Fitness Club',
      ownerName: 'Marcus Webb',
      ownerEmail: 'marcus@oakwoodfitness.com',
      businessType: 'gym',
      plan: 'growth',
      status: 'pending',
      submittedAt: '2026-04-06T10:22:00Z',
      reviewedAt: null,
      reviewedBy: null,
      notes: null,
      website: 'oakwoodfitness.com',
      memberCount: 120,
    },
    {
      id: 'ob-2',
      tenantName: 'Sunrise Apartments',
      ownerName: 'Priya Nair',
      ownerEmail: 'priya@sunriseapts.com',
      businessType: 'apartment',
      plan: 'pro',
      status: 'pending',
      submittedAt: '2026-04-07T08:15:00Z',
      reviewedAt: null,
      reviewedBy: null,
      notes: null,
      website: null,
      memberCount: 200,
    },
    {
      id: 'ob-3',
      tenantName: 'Coach Derek Online',
      ownerName: 'Derek Santos',
      ownerEmail: 'derek@derekfitness.com',
      businessType: 'online_coach',
      plan: 'starter',
      status: 'pending',
      submittedAt: '2026-04-08T14:05:00Z',
      reviewedAt: null,
      reviewedBy: null,
      notes: null,
      website: 'derekfitness.com',
      memberCount: 45,
    },
  ],
  meta: { total: 3, page: 1, limit: 20, totalPages: 1 },
}

export const MOCK_TENANTS: PaginatedResponse<TenantListItem> = {
  data: [],
  meta: { total: 0, page: 1, limit: 50, totalPages: 0 },
}

export const MOCK_OWNER_GROUPS: OwnerGroupListItem[] = [
  {
    id: 'og1',
    name: 'Meridian Properties LLC',
    owner_full_name: 'Marcus Webb',
    owner_email: 'marcus@meridianprops.com',
    owner_status: 'active',
    location_count: 2,
    total_units: 205,
    total_mrr: 4500,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'og2',
    name: 'Sunrise Communities',
    owner_full_name: 'Priya Nair',
    owner_email: 'priya@sunriseapts.com',
    owner_status: 'invited',
    location_count: 1,
    total_units: 200,
    total_mrr: 2800,
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 'og3',
    name: 'Oakwood Real Estate Group',
    owner_full_name: 'David Osei',
    owner_email: 'david@oakwoodre.com',
    owner_status: 'password_set',
    location_count: 1,
    total_units: 45,
    total_mrr: 900,
    created_at: '2025-02-10T00:00:00Z',
  },
]

export const MOCK_SUPPORT_TICKETS: PaginatedResponse<SupportTicket> = {
  data: [
    {
      id: 'tk-1',
      subject: 'Members unable to log in after update',
      description: 'Several residents are reporting login failures since the 2.4 update.',
      status: 'open',
      priority: 'urgent',
      tenantId: '1',
      tenantName: 'Riverside Apartments',
      submittedBy: 'Sarah Kim',
      submittedByEmail: 'sarah@riversidelivng.com',
      assignedTo: null,
      createdAt: '2026-04-07T09:30:00Z',
      updatedAt: '2026-04-07T09:30:00Z',
      resolvedAt: null,
    },
    {
      id: 'tk-2',
      subject: 'Stripe billing not reflecting discount',
      description: 'Promo code SPRING20 applied but invoice still shows full price.',
      status: 'open',
      priority: 'high',
      tenantId: '2',
      tenantName: 'FitLife Coaching',
      submittedBy: 'Jordan Lee',
      submittedByEmail: 'jordan@fitlifecoaching.com',
      assignedTo: null,
      createdAt: '2026-04-07T14:10:00Z',
      updatedAt: '2026-04-07T14:10:00Z',
      resolvedAt: null,
    },
    {
      id: 'tk-3',
      subject: 'Branding logo not saving correctly',
      description: 'Uploaded a new logo but the old one still shows in the app.',
      status: 'open',
      priority: 'medium',
      tenantId: '3',
      tenantName: 'Meridian Living',
      submittedBy: 'Aisha Patel',
      submittedByEmail: 'aisha@meridianliving.com',
      assignedTo: null,
      createdAt: '2026-04-08T11:00:00Z',
      updatedAt: '2026-04-08T11:00:00Z',
      resolvedAt: null,
    },
  ],
  meta: { total: 3, page: 1, limit: 20, totalPages: 1 },
}
